name: attributeModifierRemover
version: '1.0-SNAPSHOT'
main: dueris.attributeModifierRemover.AttributeModifierRemover
api-version: '1.21'

commands:
  attributeremove:
    description: Remove an attribute modifier from a player or players (supports selectors)
    usage: /<command> <target> <attribute> <id|ALL> - target can be player name or selector (@a,@p,etc)
    aliases: [atm]
